# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sledge-Plugin-Email-Japanese
version:      0.03
version_from: lib/Sledge/Plugin/Email/Japanese.pm
installdirs:  site
requires:
    Class::Accessor:               0.22
    File::Slurp:                   9999.09
    MIME::Lite::TT::Japanese:      0.07
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
